replicaCount: 1

image:
  repository: ghcr.io/thuanpham582002/mlflow
  tag: v3.5.2-amd64
  pullPolicy: IfNotPresent

default_artifact_root: "s3://datalake/mlflow/artifacts"



db:
  default:
    enabled: false
  ## type can be 'postgresql', 'mysql' or any other db type that can be used in a db_uri
  type: postgresql
  host: postgresql
  port: 5432
  user: admin
  password: password
  database: postgres

minio:
  url: minio.default.svc.cluster.local:9000
  accesskey: secret
  secretkey: secret

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  annotations: {}
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:

  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
  tls: []
  hosts: [mlflow.test]
  path: /

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Environment variables matching your deployment
extraEnv:
  - name: MLFLOW_SERVER_HOST
    value: "0.0.0.0"
  - name: MLFLOW_SERVER_PORT
    value: "5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://10.24.10.11:30900"
  - name: MLFLOW_S3_IGNORE_TLS
    value: "true"
  - name: AWS_DEFAULT_REGION
    value: "us-east-1"

# volumes:
#   - name: minio
#     persistentVolumeClaim:
#       claimName: minio

nodeSelector: {}

tolerations: []

affinity: {}
