apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  backend-store-uri: "postgresql://mlflow:mlflow_password@pgsql-cluster-rw.postgresql-cluster:5432/mlflow"
  artifact-root: "s3://mlflow-artifacts/mlflow"
  mlflow-config: |
    [server]
    host = 0.0.0.0
    port = 5000
    workers = 4
    default_artifact_root = s3://mlflow-artifacts/mlflow

    [database]
    uri = postgresql://mlflow:mlflow_password@pgsql-cluster-rw.postgresql-cluster:5432/mlflow