apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlflow

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml     
  - postgresql-setup.yaml
  - deployment.yaml
  - service.yaml
  - role.yaml

commonLabels:
  app.kubernetes.io/name: mlflow
  app.kubernetes.io/component: mlflow
  app.kubernetes.io/part-of: mlflow

# commonAnnotations:
#   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

# patches:
#   - target:
#       kind: Namespace
#       name: mlflow
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-5"
#   - target:
#       kind: Secret
#       name: mlflow-secrets
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-4"
#   - target:
#       kind: Secret
#       name: mlflow-minio-secrets
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-4"
#   - target:
#       kind: Secret
#       name: pg-superuser
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-4"
#   - target:
#       kind: ConfigMap
#       name: mlflow-config
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-4"
#   - target:
#       kind: Job
#       name: postgresql-mlflow-setup
#     patch: |-
#       - op: add
#         path: /metadata/annotations/argocd.argoproj.io~1sync-wave
#         value: "-1"